### ISSUE TITLE
Rename parameter in commands.dump_defaults

### ISSUE THREAD

**Issue by gastronomyk** [gastronomyk/SimCADO#7]
From Oliver:

To dump a file with all keywords, use:                #
    >>>  sim.commands.dump_defaults(filename, type="all") #

in

To dump a file with all keywords, use:                     #
    >>>  sim.commands.dump_defaults(filename, selection="all") #

**Comment by oczoske** [comment]
Changed in module docstring. Needs to be moved to website.
